# Generated by Django 5.1.4 on 2024-12-16 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matatus", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bustrip",
            name="route",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="matatus.route",
            ),
        ),
    ]
