# Generated by Django 5.1.4 on 2024-12-16 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matatus", "0002_bustrip_route"),
    ]

    operations = [
        migrations.AddField(
            model_name="bustrip",
            name="time",
            field=models.DateTimeField(null=True),
        ),
    ]
