# Generated by Django 5.1.4 on 2024-12-16 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matatus", "0003_bustrip_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bus",
            name="booked_capacity",
        ),
        migrations.RemoveField(
            model_name="bus",
            name="fully_booked",
        ),
        migrations.AddField(
            model_name="bustrip",
            name="fully_booked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="bustrip",
            name="total_tickets",
            field=models.IntegerField(default=0),
        ),
    ]
