# Generated by Django 5.1.4 on 2024-12-16 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matatus", "0004_remove_bus_booked_capacity_remove_bus_fully_booked_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bustrip",
            name="fare",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
