# Generated by Django 5.1.4 on 2024-12-16 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matatus", "0005_bustrip_fare"),
    ]

    operations = [
        migrations.AddField(
            model_name="bustrip",
            name="completed",
            field=models.BooleanField(default=False),
        ),
    ]
