# Generated by Django 5.1.4 on 2024-12-23 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matatus", "0006_bustrip_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="sacco",
            name="merchant_code",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
