# Generated by Django 5.1.4 on 2024-12-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="address",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
