# Generated by Django 5.1.4 on 2024-12-15 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0002_wallet_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallettransaction",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
