# Generated by Django 5.1.4 on 2024-12-16 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("matatus", "0006_bustrip_completed"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("number_of_seats", models.IntegerField(default=1)),
                ("seat_numbers", models.JSONField(default=list)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=100),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Paid", "Paid"),
                            ("Cancelled", "Cancelled"),
                            ("Complete", "Complete"),
                            ("Pending Payment", "Pending Payment"),
                        ],
                        default="Pending Payment",
                        max_length=255,
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="matatus.bustrip",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
